-- Esquema de producción tal como estaba el 25/09/2026, ANTES de las
-- migraciones de supabase/migrations/ (se creó a mano desde el panel).
-- Exportado del catálogo de Postgres. Sirve para reconstruir la base en un
-- proyecto nuevo (staging o recuperación): aplicar este archivo y después las
-- migraciones en orden.
--
-- Redactado: el secreto del webhook de matching (<SECRETO_MATCHING>) y la
-- dirección de n8n (<URL_N8N>). Cargar los valores reales a mano.
-- Nota: el export tenía dos detalles que se corrigen al aplicarlo:
--   storage.buckets public = true (no "t") y statement_timeout entre comillas.

-- ===== Secuencias =====
create sequence if not exists public.canjes_id_seq;
create sequence if not exists public.consultas_id_seq;
create sequence if not exists public.credenciales_id_seq;
create sequence if not exists public.publicaciones_id_seq;
create sequence if not exists public.reputacion_id_seq;
create sequence if not exists public.visitas_perfil_id_seq;

-- ===== Tablas =====
create table public.proveedores (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  nombre text not null,
  email text not null,
  telefono text not null,
  rubro text not null,
  zona text not null,
  precio_desde numeric not null,
  precio_hasta numeric not null,
  disponibilidad text not null,
  descripcion text not null,
  user_id uuid,
  rubro_personalizado text
);
create table public.solicitudes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  nombre_cliente text,
  email_cliente text,
  telefono_cliente text,
  servicio_necesitado text,
  zona text,
  presupuesto numeric,
  urgencia text,
  descripcion text,
  estado text,
  user_id uuid,
  foto_url text,
  cupo smallint default 5 not null
);
create table public.matches (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  solicitud_id bigint not null,
  proveedor_id bigint,
  estado text
);
create table public.mensajes (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone default now() not null,
  match_id bigint,
  remitente_tipo text,
  contenido text,
  leido boolean,
  tipo text default 'texto'::text not null,
  monto numeric,
  incluye text,
  plazo text,
  estado_presupuesto text,
  pago_id text,
  pago_estado text,
  jurisdiccion_proveedor text,
  jurisdiccion_trabajo text,
  zona_proveedor text,
  zona_trabajo text,
  trabajo_estado text
);
create table public.cuentas_mp (
  user_id uuid not null,
  created_at timestamp with time zone default now(),
  mp_user_id text,
  access_token text,
  refresh_token text,
  estado text default 'conectada'::text,
  public_key text
);
create table public.perfil_proveedor (
  user_id uuid not null,
  created_at timestamp with time zone default now(),
  nombre text,
  titular text,
  bio text,
  anios_exp integer,
  web text,
  trabajos_hechos integer default 0
);
create table public.credenciales (
  id bigint default nextval('credenciales_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  user_id uuid not null,
  tipo text,
  titulo text,
  donde text,
  desde text,
  hasta text,
  detalle text
);
create table public.publicaciones (
  id bigint default nextval('publicaciones_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  user_id uuid not null,
  tipo text,
  titulo text,
  cuerpo text,
  precio numeric,
  vence date,
  estado text default 'publicado'::text,
  fotos jsonb
);
create table public.visitas_perfil (
  id bigint default nextval('visitas_perfil_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  perfil_user_id uuid not null,
  visitante uuid
);
create table public.canjes (
  id bigint default nextval('canjes_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  user_id uuid not null,
  xp_usado integer not null,
  beneficio text,
  porcentaje integer,
  estado text default 'disponible'::text
);
create table public.consultas (
  id bigint default nextval('consultas_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  user_id uuid,
  modo text,
  pregunta text,
  respuesta text,
  revisar boolean default false,
  resuelto boolean default false
);
create table public.reputacion (
  id bigint default nextval('reputacion_id_seq'::regclass) not null,
  created_at timestamp with time zone default now(),
  match_id bigint,
  proveedor_user_id uuid not null,
  cliente_user_id uuid,
  puntaje integer,
  atributos jsonb,
  resumen text,
  comentario text
);
create table public.interesados (
  id bigint generated always as identity not null,
  solicitud_id bigint not null,
  proveedor_id bigint not null,
  user_id uuid default auth.uid() not null,
  created_at timestamp with time zone default now() not null
);
create table public.bajas (
  id uuid default gen_random_uuid() not null,
  created_at timestamp with time zone default now() not null,
  motivo text,
  era_de text
);
create table public.push_subscripciones (
  id bigint generated always as identity not null,
  user_id uuid default auth.uid() not null,
  endpoint text not null,
  p256dh text not null,
  auth_clave text not null,
  user_agent text,
  creado_en timestamp with time zone default now() not null
);
create table public.config_app (
  clave text not null,
  valor text,
  actualizado_en timestamp with time zone default now() not null
);
create table public.novedades (
  id bigint generated always as identity not null,
  orden integer not null,
  dirigido_a text default 'todos'::text not null,
  titulo text not null,
  cuerpo text not null,
  activo boolean default true not null,
  creado_en timestamp with time zone default now() not null
);
create table public.novedades_envios (
  user_id uuid not null,
  canal text not null,
  ultimo_orden integer,
  enviado_en timestamp with time zone
);
create table public.video_jobs (
  id uuid default gen_random_uuid() not null,
  tema text not null,
  guion jsonb,
  estado text default 'creado'::text not null,
  veo_operation_name text,
  veo_video_uri text,
  video_local_url text,
  plataformas jsonb default '[]'::jsonb not null,
  publicaciones jsonb default '{}'::jsonb not null,
  intentos_veo integer default 0 not null,
  intentos_publicacion integer default 0 not null,
  error text,
  creado_en timestamp with time zone default now() not null,
  actualizado_en timestamp with time zone default now() not null
);
create table public.oauth_states (
  nonce uuid default gen_random_uuid() not null,
  user_id uuid not null,
  proveedor text default 'mercadopago'::text not null,
  creado_en timestamp with time zone default now() not null
);
alter sequence public.reputacion_id_seq owned by public.reputacion.id;
alter sequence public.credenciales_id_seq owned by public.credenciales.id;
alter sequence public.canjes_id_seq owned by public.canjes.id;
alter sequence public.publicaciones_id_seq owned by public.publicaciones.id;
alter sequence public.visitas_perfil_id_seq owned by public.visitas_perfil.id;
alter sequence public.consultas_id_seq owned by public.consultas.id;

-- ===== Restricciones =====
alter table bajas add constraint bajas_pkey PRIMARY KEY (id);
alter table canjes add constraint canjes_pkey PRIMARY KEY (id);
alter table config_app add constraint config_app_pkey PRIMARY KEY (clave);
alter table consultas add constraint consultas_pkey PRIMARY KEY (id);
alter table credenciales add constraint credenciales_pkey PRIMARY KEY (id);
alter table cuentas_mp add constraint cuentas_mp_pkey PRIMARY KEY (user_id);
alter table interesados add constraint interesados_pkey PRIMARY KEY (id);
alter table matches add constraint matches_pkey PRIMARY KEY (id);
alter table mensajes add constraint mensajes_pkey PRIMARY KEY (id);
alter table novedades add constraint novedades_pkey PRIMARY KEY (id);
alter table novedades_envios add constraint novedades_envios_pkey PRIMARY KEY (user_id, canal);
alter table oauth_states add constraint oauth_states_pkey PRIMARY KEY (nonce);
alter table perfil_proveedor add constraint perfil_proveedor_pkey PRIMARY KEY (user_id);
alter table proveedores add constraint proveedores_pkey PRIMARY KEY (id);
alter table publicaciones add constraint publicaciones_pkey PRIMARY KEY (id);
alter table push_subscripciones add constraint push_subscripciones_pkey PRIMARY KEY (id);
alter table reputacion add constraint reputacion_pkey PRIMARY KEY (id);
alter table solicitudes add constraint solicitudes_pkey PRIMARY KEY (id);
alter table video_jobs add constraint video_jobs_pkey PRIMARY KEY (id);
alter table visitas_perfil add constraint visitas_perfil_pkey PRIMARY KEY (id);
alter table interesados add constraint interesados_solicitud_id_proveedor_id_key UNIQUE (solicitud_id, proveedor_id);
alter table mensajes add constraint mensajes_estado_presupuesto_check CHECK ((estado_presupuesto = ANY (ARRAY['pendiente'::text, 'aceptado'::text, 'rechazado'::text])));
alter table mensajes add constraint mensajes_tipo_check CHECK ((tipo = ANY (ARRAY['texto'::text, 'presupuesto'::text])));
alter table mensajes add constraint mensajes_trabajo_estado_check CHECK (((trabajo_estado IS NULL) OR (trabajo_estado = 'terminado'::text)));
alter table novedades add constraint novedades_dirigido_a_check CHECK ((dirigido_a = ANY (ARRAY['todos'::text, 'cliente'::text, 'proveedor'::text])));
alter table novedades add constraint novedades_orden_key UNIQUE (orden);
alter table novedades_envios add constraint novedades_envios_canal_check CHECK ((canal = ANY (ARRAY['push'::text, 'mail'::text])));
alter table push_subscripciones add constraint push_subscripciones_endpoint_key UNIQUE (endpoint);
alter table reputacion add constraint reputacion_match_id_key UNIQUE (match_id);
alter table video_jobs add constraint video_jobs_estado_check CHECK ((estado = ANY (ARRAY['creado'::text, 'guion_listo'::text, 'veo_enviado'::text, 'veo_generando'::text, 'veo_listo'::text, 'veo_fallido'::text, 'publicando'::text, 'publicado'::text, 'publicado_parcial'::text, 'fallido'::text])));
alter table canjes add constraint canjes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table credenciales add constraint credenciales_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table cuentas_mp add constraint cuentas_mp_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table interesados add constraint interesados_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES proveedores(id) ON DELETE CASCADE;
alter table interesados add constraint interesados_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id) ON DELETE CASCADE;
alter table matches add constraint matches_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES proveedores(id);
alter table matches add constraint matches_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id);
alter table mensajes add constraint mensajes_match_id_fkey FOREIGN KEY (match_id) REFERENCES matches(id);
alter table oauth_states add constraint oauth_states_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table perfil_proveedor add constraint perfil_proveedor_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table proveedores add constraint proveedores_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);
alter table publicaciones add constraint publicaciones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table solicitudes add constraint solicitudes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);

-- ===== Índices =====
CREATE INDEX interesados_solicitud_idx ON public.interesados USING btree (solicitud_id);
CREATE INDEX interesados_user_idx ON public.interesados USING btree (user_id);
CREATE INDEX push_subscripciones_user_idx ON public.push_subscripciones USING btree (user_id);
CREATE UNIQUE INDEX matches_solicitud_proveedor_unico ON public.matches USING btree (solicitud_id, proveedor_id);

-- ===== Funciones =====
CREATE OR REPLACE FUNCTION public.abrir_chat_al_interesarse()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  -- Un match por par pedido/proveedor. Si la app ya lo habia sugerido y el
  -- proveedor ademas se anota, no se duplica la conversacion: se deja la que
  -- ya existe, que puede tener mensajes adentro.
  if exists (
    select 1 from public.matches
    where solicitud_id = new.solicitud_id
      and proveedor_id = new.proveedor_id
  ) then
    return new;
  end if;

  -- 'interesado' se distingue a proposito de 'sugerido': uno lo armo la app,
  -- el otro lo pidio el proveedor. La app los muestra distinto, porque
  -- decirle "te lo recomendamos" a alguien que se ofrecio solo seria falso.
  insert into public.matches (solicitud_id, proveedor_id, estado)
  values (new.solicitud_id, new.proveedor_id, 'interesado');

  -- El pedido deja de estar "buscando" en la pantalla del cliente.
  update public.solicitudes
     set estado = 'con_match'
   where id = new.solicitud_id
     and estado = 'pendiente';

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.borrar_mi_cuenta(motivo_baja text DEFAULT NULL::text)
 RETURNS json
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'auth'
AS $function$
declare
  yo        uuid := auth.uid();
  mi_rol    text;
  mis_prov  uuid[];
  mis_sol   uuid[];
  mis_match uuid[];
  borradas  int := 0;
begin
  -- Nunca confiar en un id que venga de afuera: se usa el del token.
  if yo is null then
    raise exception 'sin sesión';
  end if;

  select coalesce(raw_user_meta_data->>'rol', 'cliente')
    into mi_rol from auth.users where id = yo;

  -- Qué es mío, resuelto una sola vez
  select coalesce(array_agg(id), '{}') into mis_prov
    from public.proveedores where user_id = yo;

  select coalesce(array_agg(id), '{}') into mis_sol
    from public.solicitudes where user_id = yo;

  select coalesce(array_agg(id), '{}') into mis_match
    from public.matches
    where solicitud_id = any(mis_sol) or proveedor_id = any(mis_prov);

  -- ── Calificaciones ────────────────────────────────────────────────────
  -- Las que YO dejé sobre un Proveedor: sobreviven, pero dejan de decir
  -- quién las dejó. Es la reputación de otra persona, no mía.
  update public.reputacion
     set cliente_user_id = null,
         match_id        = null
   where cliente_user_id = yo;

  -- Las que son SOBRE MÍ como Proveedor: se van con el perfil. Sin perfil
  -- no hay reputación que sostener.
  delete from public.reputacion where proveedor_user_id = yo;

  -- ── Conversaciones ────────────────────────────────────────────────────
  delete from public.mensajes    where match_id = any(mis_match);
  delete from public.matches     where id       = any(mis_match);
  delete from public.interesados where user_id  = yo or solicitud_id = any(mis_sol);

  -- ── Pedidos y perfiles ────────────────────────────────────────────────
  delete from public.solicitudes      where user_id = yo;
  delete from public.publicaciones    where user_id = yo;
  delete from public.credenciales     where user_id = yo;
  delete from public.perfil_proveedor where user_id = yo;
  delete from public.proveedores      where user_id = yo;

  -- ── Rastros de uso ────────────────────────────────────────────────────
  delete from public.consultas      where user_id        = yo;
  delete from public.canjes         where user_id        = yo;
  delete from public.visitas_perfil where perfil_user_id = yo;

  -- CONFIRMAR: si 'visitante' guarda el id del usuario que visitó, esta
  -- línea hace falta y hay que descomentarla. Si guarda otra cosa (una IP,
  -- un identificador de sesión), dejala comentada y decime qué guarda.
  -- delete from public.visitas_perfil where visitante = yo::text;

  -- ── Mercado Pago ──────────────────────────────────────────────────────
  -- Acá viven access_token y refresh_token: credenciales vivas. Borrar la
  -- fila es obligatorio, pero NO revoca el permiso del lado de Mercado
  -- Pago. Eso hay que hacerlo con su API, desde n8n, antes de llamar acá.
  delete from public.cuentas_mp where user_id = yo;

  -- ── Lo que sobrevive ──────────────────────────────────────────────────
  -- El punto 6.1 de la Política conserva el registro contable de las
  -- operaciones cobradas: identificador, fecha, monto, comisión, CUIT y
  -- número de comprobante.
  --
  -- HOY NO SE CONSERVA NADA, y es correcto: no existe todavía la tabla de
  -- operaciones cobradas ni la emisión de comprobantes, así que no hay
  -- registro contable que guardar. La promesa se cumple de forma vacía.
  --
  -- Cuando exista esa tabla, va acá el UPDATE que desvincula la operación
  -- de la persona conservando los campos fiscales. No antes.

  -- ── Motivo, sin dueño ─────────────────────────────────────────────────
  if motivo_baja is not null and length(trim(motivo_baja)) > 0 then
    insert into public.bajas (motivo, era_de) values (trim(motivo_baja), mi_rol);
  end if;

  -- ── La cuenta ─────────────────────────────────────────────────────────
  delete from auth.users where id = yo;
  get diagnostics borradas = row_count;

  return json_build_object('ok', true, 'cuenta_borrada', borradas = 1);
end;
$function$
;

CREATE OR REPLACE FUNCTION public.chequear_cupo()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  tomados int;
  limite  int;
begin
  -- El for update serializa: dos proveedores que toquen "me interesa" en el
  -- mismo instante no pueden pasar los dos el chequeo.
  select cupo into limite from public.solicitudes where id = new.solicitud_id for update;
  if limite is null then
    raise exception 'ese pedido no existe' using errcode = 'P0002';
  end if;

  select count(*) into tomados from public.interesados where solicitud_id = new.solicitud_id;
  if tomados >= limite then
    raise exception 'ese pedido ya tiene el cupo completo' using errcode = 'P0001';
  end if;

  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.es_mi_proveedor(pid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from proveedores p
    where p.id = pid and p.user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.es_mi_solicitud(sid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from solicitudes s
    where s.id = sid and s.user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.marcar_publicacion(p_id uuid, p_plataforma text, p_resultado jsonb)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.video_jobs
  set publicaciones = coalesce(publicaciones, '{}'::jsonb) || jsonb_build_object(p_plataforma, p_resultado),
      estado = 'publicado'
  where id = p_id;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.notificar_evento_push()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'net'
AS $function$
declare
  destinatario   uuid;
  titulo         text;
  cuerpo         text;
  url_push       text := 'https://qglsonbcsncgekzbfafk.supabase.co/functions/v1/quick-service';
  secreto        text;
  rubro          text;
begin
  if coalesce(new.tipo, '') <> 'presupuesto' then
    return new;
  end if;

  -- ── 1) Presupuesto nuevo → avisarle al cliente ─────────────────────────
  if tg_op = 'INSERT' and coalesce(new.estado_presupuesto,'') = 'pendiente' then
    select s.user_id, s.servicio_necesitado into destinatario, rubro
      from public.matches m
      join public.solicitudes s on s.id = m.solicitud_id
     where m.id = new.match_id;

    titulo := 'Te llegó un presupuesto';
    cuerpo := 'Te ofrecieron ' || to_char(new.monto, 'FM999G999G999') || ' pesos' ||
              (case when rubro is not null then ' para tu pedido de ' || rubro else '' end) ||
              '. Mirá los detalles.';

  -- ── 2) Presupuesto aceptado → avisarle al proveedor ────────────────────
  elsif tg_op = 'UPDATE'
        and new.estado_presupuesto = 'aceptado'
        and old.estado_presupuesto is distinct from 'aceptado' then

    select p.user_id into destinatario
      from public.matches m
      join public.proveedores p on p.id = m.proveedor_id
     where m.id = new.match_id;

    titulo := 'Te aceptaron un presupuesto';
    cuerpo := 'Te aceptaron el de ' || to_char(new.monto, 'FM999G999G999') || ' pesos. Ya podés arrancar.';

  -- ── 3) Presupuesto rechazado → avisarle al proveedor ───────────────────
  elsif tg_op = 'UPDATE'
        and new.estado_presupuesto = 'rechazado'
        and old.estado_presupuesto is distinct from 'rechazado' then

    select p.user_id into destinatario
      from public.matches m
      join public.proveedores p on p.id = m.proveedor_id
     where m.id = new.match_id;

    titulo := 'No te aceptaron este presupuesto';
    cuerpo := 'Podés mandar otro con otras condiciones si querés.';

  -- ── 4) Trabajo marcado terminado → avisarle al cliente ─────────────────
  elsif tg_op = 'UPDATE'
        and new.trabajo_estado = 'terminado'
        and old.trabajo_estado is distinct from 'terminado' then

    select s.user_id into destinatario
      from public.matches m
      join public.solicitudes s on s.id = m.solicitud_id
     where m.id = new.match_id;

    titulo := 'Marcaron tu pedido como terminado';
    cuerpo := 'Revisalo y pagalo cuando estés conforme.';

  -- ── 5) Pago cobrado → avisarle al proveedor ────────────────────────────
  elsif tg_op = 'UPDATE'
        and new.pago_estado = 'cobrado'
        and old.pago_estado is distinct from 'cobrado' then

    select p.user_id into destinatario
      from public.matches m
      join public.proveedores p on p.id = m.proveedor_id
     where m.id = new.match_id;

    titulo := 'Te pagaron';
    cuerpo := 'Se acreditaron ' || to_char(new.monto, 'FM999G999G999') || ' pesos por tu trabajo.';

  else
    return new;
  end if;

  if destinatario is null then
    return new;
  end if;

  select decrypted_secret into secreto
    from vault.decrypted_secrets where name = 'push_firma_quick_service';

  perform net.http_post(
    url     := url_push,
    body    := jsonb_build_object(
                 'user_id', destinatario,
                 'titulo',  titulo,
                 'cuerpo',  cuerpo,
                 'url',     '/',
                 'tipo',    'servicio'
               ),
    headers := jsonb_build_object(
                 'Content-Type', 'application/json',
                 'x-tratto-firma', secreto
               )
  );

  return new;
exception
  when others then
    return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.novedades_a_mandar(p_canal text, p_intervalo_dias integer)
 RETURNS TABLE(destinatario uuid, novedad_id bigint, titulo text, cuerpo text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  fila     record;
  v_id     bigint;
  v_titulo text;
  v_cuerpo text;
  v_orden  int;
begin
  if p_canal not in ('push','mail') then
    raise exception 'canal inválido: %', p_canal;
  end if;

  for fila in
    select u.id as uid, coalesce(u.raw_user_meta_data->>'rol','cliente') as rol,
           ne.ultimo_orden, ne.enviado_en
    from auth.users u
    left join public.novedades_envios ne on ne.user_id = u.id and ne.canal = p_canal
    where (u.raw_user_meta_data->>'publicidad_permiso')::boolean is true
      and (ne.enviado_en is null or ne.enviado_en < now() - (p_intervalo_dias || ' days')::interval)
  loop
    v_id := null; v_titulo := null; v_cuerpo := null; v_orden := null;

    -- la próxima en su rotación: activa, para su rol (o para todos), con
    -- orden mayor a la última que le tocó.
    select n.id, n.titulo, n.cuerpo, n.orden into v_id, v_titulo, v_cuerpo, v_orden
      from public.novedades n
     where n.activo
       and n.dirigido_a in ('todos', fila.rol)
       and (fila.ultimo_orden is null or n.orden > fila.ultimo_orden)
     order by n.orden
     limit 1;

    -- se acabó la lista: se vuelve al principio.
    if v_id is null then
      select n.id, n.titulo, n.cuerpo, n.orden into v_id, v_titulo, v_cuerpo, v_orden
        from public.novedades n
       where n.activo
         and n.dirigido_a in ('todos', fila.rol)
       order by n.orden
       limit 1;
    end if;

    if v_id is null then
      continue; -- no hay ninguna novedad activa para este rol
    end if;

    insert into public.novedades_envios (user_id, canal, ultimo_orden, enviado_en)
    values (fila.uid, p_canal, v_orden, now())
    on conflict (user_id, canal) do update
      set ultimo_orden = excluded.ultimo_orden, enviado_en = excluded.enviado_en;

    destinatario := fila.uid;
    novedad_id   := v_id;
    titulo       := v_titulo;
    cuerpo       := v_cuerpo;
    return next;
  end loop;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.proteger_mensajes()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare es_cliente boolean; es_proveedor boolean;
begin
  -- n8n (service_role) y las funciones SECURITY DEFINER no pasan por estas reglas.
  -- Se mira current_user y no auth.role(): dentro de sumar_trabajo() auth.role()
  -- sigue diciendo 'authenticated' y bloquearia la suma legitima de trabajos.
  if current_user not in ('authenticated', 'anon') then return new; end if;
  select coalesce(bool_or(s.user_id = auth.uid()), false), coalesce(bool_or(p.user_id = auth.uid()), false)
    into es_cliente, es_proveedor
  from public.matches m
  left join public.solicitudes s on s.id = m.solicitud_id
  left join public.proveedores p on p.id = m.proveedor_id
  where m.id = new.match_id;
  if tg_op = 'INSERT' then
    new.pago_estado := null; new.pago_id := null; new.trabajo_estado := null;
    new.jurisdiccion_proveedor := null; new.jurisdiccion_trabajo := null;
    new.zona_proveedor := null; new.zona_trabajo := null;
    if new.tipo = 'presupuesto' then
      if not es_proveedor then raise exception 'Solo el proveedor puede mandar un presupuesto.'; end if;
      new.remitente_tipo := 'proveedor'; new.estado_presupuesto := 'pendiente';
    elsif new.tipo = 'texto' then
      new.estado_presupuesto := null; new.monto := null; new.incluye := null; new.plazo := null;
      if es_cliente and not es_proveedor then new.remitente_tipo := 'cliente';
      elsif es_proveedor and not es_cliente then new.remitente_tipo := 'proveedor'; end if;
    else raise exception 'Tipo de mensaje no permitido.'; end if;
    return new;
  end if;
  if new.id is distinct from old.id or new.created_at is distinct from old.created_at
     or new.match_id is distinct from old.match_id or new.remitente_tipo is distinct from old.remitente_tipo
     or new.tipo is distinct from old.tipo or new.contenido is distinct from old.contenido
     or new.monto is distinct from old.monto or new.incluye is distinct from old.incluye
     or new.plazo is distinct from old.plazo or new.pago_estado is distinct from old.pago_estado
     or new.pago_id is distinct from old.pago_id
     or new.jurisdiccion_proveedor is distinct from old.jurisdiccion_proveedor
     or new.jurisdiccion_trabajo is distinct from old.jurisdiccion_trabajo
     or new.zona_proveedor is distinct from old.zona_proveedor or new.zona_trabajo is distinct from old.zona_trabajo
  then raise exception 'No se puede modificar un mensaje ya enviado.'; end if;
  if new.estado_presupuesto is distinct from old.estado_presupuesto then
    if not es_cliente then raise exception 'Solo el cliente puede aceptar o rechazar el presupuesto.'; end if;
    if old.tipo <> 'presupuesto' or old.estado_presupuesto is distinct from 'pendiente'
       or new.estado_presupuesto not in ('aceptado', 'rechazado') then
      raise exception 'Ese presupuesto ya no se puede responder.'; end if;
  end if;
  if new.trabajo_estado is distinct from old.trabajo_estado then
    if not es_proveedor then raise exception 'Solo el proveedor puede marcar el trabajo como terminado.'; end if;
    if old.tipo <> 'presupuesto' or new.estado_presupuesto is distinct from 'aceptado'
       or old.trabajo_estado is not null or new.trabajo_estado is distinct from 'terminado' then
      raise exception 'Ese trabajo no se puede marcar como terminado.'; end if;
  end if;
  return new;
end; $function$
;

CREATE OR REPLACE FUNCTION public.proteger_perfil_proveedor()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if current_user not in ('authenticated', 'anon') then return new; end if;
  if tg_op = 'UPDATE' then new.trabajos_hechos := old.trabajos_hechos; else new.trabajos_hechos := 0; end if;
  return new;
end; $function$
;

CREATE OR REPLACE FUNCTION public.proveedor_visible(pid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from matches m
    join solicitudes s on s.id = m.solicitud_id
    where m.proveedor_id = pid and s.user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.registrar_push_subscripcion(p_endpoint text, p_p256dh text, p_auth_clave text, p_user_agent text DEFAULT NULL::text)
 RETURNS push_subscripciones
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  fila public.push_subscripciones;
begin
  if auth.uid() is null then
    raise exception 'sin sesión';
  end if;

  insert into public.push_subscripciones (user_id, endpoint, p256dh, auth_clave, user_agent)
  values (auth.uid(), p_endpoint, p_p256dh, p_auth_clave, p_user_agent)
  on conflict (endpoint) do update
    set user_id    = excluded.user_id,
        p256dh     = excluded.p256dh,
        auth_clave = excluded.auth_clave,
        user_agent = excluded.user_agent,
        creado_en  = now()
  returning * into fila;

  return fila;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.solicitud_visible(sid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from matches m
    join proveedores p on p.id = m.proveedor_id
    where m.solicitud_id = sid and p.user_id = auth.uid()
  );
$function$
;

CREATE OR REPLACE FUNCTION public.soy_parte_del_match(mid bigint)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  select exists (
    select 1 from matches m
    left join solicitudes s on s.id = m.solicitud_id
    left join proveedores p on p.id = m.proveedor_id
    where m.id = mid
      and (s.user_id = auth.uid() or p.user_id = auth.uid())
  );
$function$
;

CREATE OR REPLACE FUNCTION public.sumar_trabajo()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if new.tipo = 'presupuesto'
     and new.estado_presupuesto = 'aceptado'
     and old.estado_presupuesto is distinct from 'aceptado' then
    update perfil_proveedor pp
       set trabajos_hechos = coalesce(pp.trabajos_hechos, 0) + 1
      from matches m
      join proveedores p on p.id = m.proveedor_id
     where m.id = new.match_id and pp.user_id = p.user_id;
  end if;
  return new;
end $function$
;

CREATE OR REPLACE FUNCTION public.video_jobs_tocar_actualizado_en()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.actualizado_en = now();
  return new;
end;
$function$
;

-- ===== Vistas =====
create view public.pedidos_abiertos with (security_invoker=off) as
 SELECT id,
    created_at,
    servicio_necesitado,
    zona,
    urgencia,
    descripcion,
    foto_url,
    presupuesto,
    cupo,
    ( SELECT count(*) AS count
           FROM interesados i
          WHERE (i.solicitud_id = s.id)) AS tomados
   FROM solicitudes s
  WHERE ((estado = 'pendiente'::text) AND (created_at > (now() - '15 days'::interval)) AND (user_id <> auth.uid()) AND (( SELECT count(*) AS count
           FROM interesados i
          WHERE (i.solicitud_id = s.id)) < cupo) AND (NOT (EXISTS ( SELECT 1
           FROM (interesados i
             JOIN proveedores p ON ((p.id = i.proveedor_id)))
          WHERE ((i.solicitud_id = s.id) AND (p.user_id = auth.uid()))))) AND (EXISTS ( SELECT 1
           FROM proveedores p
          WHERE ((p.user_id = auth.uid()) AND (p.rubro = s.servicio_necesitado)))));
create view public.usuarios_publicidad with (security_invoker=off) as
 SELECT id AS user_id
   FROM auth.users
  WHERE (((raw_user_meta_data ->> 'publicidad_permiso'::text))::boolean IS TRUE);

-- ===== Triggers =====
CREATE TRIGGER interesados_abren_chat AFTER INSERT ON public.interesados FOR EACH ROW EXECUTE FUNCTION abrir_chat_al_interesarse();
CREATE TRIGGER interesados_cupo BEFORE INSERT ON public.interesados FOR EACH ROW EXECUTE FUNCTION chequear_cupo();
CREATE TRIGGER matching_proveedores AFTER INSERT ON public.proveedores FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('<URL_N8N>', 'POST', '{"Content-type":"application/json","x-tratto-secreto":"<SECRETO_MATCHING>"}', '{}', '5000');
CREATE TRIGGER matching_solicitudes AFTER INSERT ON public.solicitudes FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('<URL_N8N>', 'POST', '{"Content-type":"application/json","x-tratto-secreto":"<SECRETO_MATCHING>"}', '{}', '5000');
CREATE TRIGGER mensajes_notificar_push AFTER INSERT OR UPDATE ON public.mensajes FOR EACH ROW EXECUTE FUNCTION notificar_evento_push();
CREATE TRIGGER proteger_mensajes BEFORE INSERT OR UPDATE ON public.mensajes FOR EACH ROW EXECUTE FUNCTION proteger_mensajes();
CREATE TRIGGER proteger_perfil_proveedor BEFORE INSERT OR UPDATE ON public.perfil_proveedor FOR EACH ROW EXECUTE FUNCTION proteger_perfil_proveedor();
CREATE TRIGGER trg_sumar_trabajo AFTER UPDATE ON public.mensajes FOR EACH ROW EXECUTE FUNCTION sumar_trabajo();
CREATE TRIGGER video_jobs_actualizado_en BEFORE UPDATE ON public.video_jobs FOR EACH ROW EXECUTE FUNCTION video_jobs_tocar_actualizado_en();

-- ===== RLS y políticas =====
alter table public.bajas enable row level security;
alter table public.canjes enable row level security;
alter table public.config_app enable row level security;
alter table public.consultas enable row level security;
alter table public.credenciales enable row level security;
alter table public.cuentas_mp enable row level security;
alter table public.interesados enable row level security;
alter table public.matches enable row level security;
alter table public.mensajes enable row level security;
alter table public.novedades enable row level security;
alter table public.novedades_envios enable row level security;
alter table public.oauth_states enable row level security;
alter table public.perfil_proveedor enable row level security;
alter table public.proveedores enable row level security;
alter table public.publicaciones enable row level security;
alter table public.push_subscripciones enable row level security;
alter table public.reputacion enable row level security;
alter table public.solicitudes enable row level security;
alter table public.video_jobs enable row level security;
alter table public.visitas_perfil enable row level security;
create policy "manejo mis canjes" on public.canjes as PERMISSIVE for ALL to public using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "credenciales visibles" on public.credenciales as PERMISSIVE for SELECT to public using ((auth.uid() IS NOT NULL));
create policy "manejo mis credenciales" on public.credenciales as PERMISSIVE for ALL to public using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "cada proveedor ve su cuenta" on public.cuentas_mp as PERMISSIVE for SELECT to public using ((auth.uid() = user_id));
create policy "veo mi cuenta de mp" on public.cuentas_mp as PERMISSIVE for SELECT to public using ((user_id = auth.uid()));
create policy "el cliente ve quien tomo su pedido" on public.interesados as PERMISSIVE for SELECT to authenticated using ((EXISTS ( SELECT 1
   FROM solicitudes s
  WHERE ((s.id = interesados.solicitud_id) AND (s.user_id = auth.uid())))));
create policy "el proveedor anota su propio interes" on public.interesados as PERMISSIVE for INSERT to authenticated with check (((user_id = auth.uid()) AND (EXISTS ( SELECT 1
   FROM proveedores p
  WHERE ((p.id = interesados.proveedor_id) AND (p.user_id = auth.uid()))))));
create policy "el proveedor ve sus propios intereses" on public.interesados as PERMISSIVE for SELECT to authenticated using ((user_id = auth.uid()));
create policy match_editar on public.matches as PERMISSIVE for UPDATE to authenticated using ((es_mi_solicitud(solicitud_id) OR es_mi_proveedor(proveedor_id))) with check ((es_mi_solicitud(solicitud_id) OR es_mi_proveedor(proveedor_id)));
create policy match_leer on public.matches as PERMISSIVE for SELECT to authenticated using ((es_mi_solicitud(solicitud_id) OR es_mi_proveedor(proveedor_id)));
create policy "el cliente responde el presupuesto" on public.mensajes as PERMISSIVE for UPDATE to public using (((tipo = 'presupuesto'::text) AND (EXISTS ( SELECT 1
   FROM (matches m
     JOIN solicitudes s ON ((s.id = m.solicitud_id)))
  WHERE ((m.id = mensajes.match_id) AND (s.user_id = auth.uid())))))) with check (((tipo = 'presupuesto'::text) AND (EXISTS ( SELECT 1
   FROM (matches m
     JOIN solicitudes s ON ((s.id = m.solicitud_id)))
  WHERE ((m.id = mensajes.match_id) AND (s.user_id = auth.uid()))))));
create policy msg_crear on public.mensajes as PERMISSIVE for INSERT to authenticated with check (soy_parte_del_match(match_id));
create policy msg_editar on public.mensajes as PERMISSIVE for UPDATE to authenticated using (soy_parte_del_match(match_id)) with check (soy_parte_del_match(match_id));
create policy msg_leer on public.mensajes as PERMISSIVE for SELECT to authenticated using (soy_parte_del_match(match_id));
create policy "creo mi perfil" on public.perfil_proveedor as PERMISSIVE for INSERT to public with check ((user_id = auth.uid()));
create policy "edito mi perfil" on public.perfil_proveedor as PERMISSIVE for UPDATE to public using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "perfil visible" on public.perfil_proveedor as PERMISSIVE for SELECT to public using ((auth.uid() IS NOT NULL));
create policy prov_borrar on public.proveedores as PERMISSIVE for DELETE to authenticated using ((user_id = auth.uid()));
create policy prov_crear on public.proveedores as PERMISSIVE for INSERT to authenticated with check ((user_id = auth.uid()));
create policy prov_editar on public.proveedores as PERMISSIVE for UPDATE to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy prov_leer on public.proveedores as PERMISSIVE for SELECT to authenticated using (((user_id = auth.uid()) OR proveedor_visible(id)));
create policy "manejo mis publicaciones" on public.publicaciones as PERMISSIVE for ALL to public using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "publicaciones visibles" on public.publicaciones as PERMISSIVE for SELECT to public using ((auth.uid() IS NOT NULL));
create policy "cada uno borra sus propios dispositivos" on public.push_subscripciones as PERMISSIVE for DELETE to authenticated using ((user_id = auth.uid()));
create policy "cada uno ve sus propios dispositivos" on public.push_subscripciones as PERMISSIVE for SELECT to authenticated using ((user_id = auth.uid()));
create policy "reputacion visible" on public.reputacion as PERMISSIVE for SELECT to public using ((auth.uid() IS NOT NULL));
create policy sol_borrar on public.solicitudes as PERMISSIVE for DELETE to authenticated using ((user_id = auth.uid()));
create policy sol_crear on public.solicitudes as PERMISSIVE for INSERT to authenticated with check ((user_id = auth.uid()));
create policy sol_editar on public.solicitudes as PERMISSIVE for UPDATE to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy sol_leer on public.solicitudes as PERMISSIVE for SELECT to authenticated using (((user_id = auth.uid()) OR solicitud_visible(id)));
create policy "registro visita" on public.visitas_perfil as PERMISSIVE for INSERT to public with check ((auth.uid() IS NOT NULL));
create policy "veo mis visitas" on public.visitas_perfil as PERMISSIVE for SELECT to public using ((perfil_user_id = auth.uid()));
create policy "borro mis fotos" on storage.objects as PERMISSIVE for DELETE to public using (((bucket_id = 'publicaciones'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "subo mis fotos" on storage.objects as PERMISSIVE for INSERT to public with check (((bucket_id = 'publicaciones'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));
create policy "veo mis fotos" on storage.objects as PERMISSIVE for SELECT to authenticated using (((bucket_id = 'publicaciones'::text) AND ((storage.foldername(name))[1] = (auth.uid())::text)));

-- ===== Permisos de tablas y vistas =====
revoke all on public.proveedores from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.proveedores to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.proveedores to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.proveedores to anon;
revoke all on public.solicitudes from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.solicitudes to service_role;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.solicitudes to authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.solicitudes to anon;
grant SELECT (created_at) on public.solicitudes to authenticated;
grant SELECT (cupo) on public.solicitudes to authenticated;
grant SELECT (descripcion) on public.solicitudes to authenticated;
grant SELECT (estado) on public.solicitudes to authenticated;
grant SELECT (foto_url) on public.solicitudes to authenticated;
grant SELECT (id) on public.solicitudes to authenticated;
grant SELECT (nombre_cliente) on public.solicitudes to authenticated;
grant SELECT (presupuesto) on public.solicitudes to authenticated;
grant SELECT (servicio_necesitado) on public.solicitudes to authenticated;
grant SELECT (urgencia) on public.solicitudes to authenticated;
grant SELECT (user_id) on public.solicitudes to authenticated;
grant SELECT (zona) on public.solicitudes to authenticated;
revoke all on public.matches from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.matches to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.matches to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.matches to anon;
revoke all on public.mensajes from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.mensajes to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.mensajes to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.mensajes to anon;
revoke all on public.cuentas_mp from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.cuentas_mp to service_role;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.cuentas_mp to authenticated;
grant INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.cuentas_mp to anon;
grant SELECT (user_id) on public.cuentas_mp to authenticated;
grant SELECT (created_at) on public.cuentas_mp to authenticated;
grant SELECT (estado) on public.cuentas_mp to authenticated;
grant SELECT (mp_user_id) on public.cuentas_mp to authenticated;
revoke all on public.perfil_proveedor from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.perfil_proveedor to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.perfil_proveedor to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.perfil_proveedor to anon;
revoke all on public.credenciales from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.credenciales to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.credenciales to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.credenciales to anon;
revoke all on public.publicaciones from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.publicaciones to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.publicaciones to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.publicaciones to anon;
revoke all on public.visitas_perfil from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.visitas_perfil to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.visitas_perfil to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.visitas_perfil to anon;
revoke all on public.canjes from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.canjes to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.canjes to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.canjes to anon;
revoke all on public.consultas from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.consultas to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.consultas to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.consultas to anon;
revoke all on public.reputacion from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.reputacion to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.reputacion to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.reputacion to anon;
revoke all on public.interesados from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.interesados to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.interesados to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.interesados to anon;
revoke all on public.pedidos_abiertos from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.pedidos_abiertos to service_role;
grant SELECT, MAINTAIN on public.pedidos_abiertos to authenticated;
revoke all on public.bajas from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.bajas to service_role;
revoke all on public.push_subscripciones from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.push_subscripciones to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.push_subscripciones to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.push_subscripciones to anon;
revoke all on public.usuarios_publicidad from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.usuarios_publicidad to service_role;
revoke all on public.config_app from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.config_app to service_role;
revoke all on public.novedades from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.novedades to service_role;
revoke all on public.novedades_envios from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.novedades_envios to service_role;
revoke all on public.video_jobs from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.video_jobs to service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.video_jobs to authenticated;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.video_jobs to anon;
revoke all on public.oauth_states from anon, authenticated, service_role;
grant INSERT, SELECT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER, MAINTAIN on public.oauth_states to service_role;

-- ===== Permisos de funciones =====
revoke execute on function abrir_chat_al_interesarse() from public, anon, authenticated;
grant execute on function abrir_chat_al_interesarse() to service_role;
revoke execute on function borrar_mi_cuenta(text) from public, anon, authenticated;
grant execute on function borrar_mi_cuenta(text) to authenticated;
grant execute on function borrar_mi_cuenta(text) to service_role;
revoke execute on function chequear_cupo() from public, anon, authenticated;
grant execute on function chequear_cupo() to service_role;
revoke execute on function es_mi_proveedor(bigint) from public, anon, authenticated;
grant execute on function es_mi_proveedor(bigint) to public;
grant execute on function es_mi_proveedor(bigint) to anon;
grant execute on function es_mi_proveedor(bigint) to authenticated;
grant execute on function es_mi_proveedor(bigint) to service_role;
revoke execute on function es_mi_solicitud(bigint) from public, anon, authenticated;
grant execute on function es_mi_solicitud(bigint) to public;
grant execute on function es_mi_solicitud(bigint) to anon;
grant execute on function es_mi_solicitud(bigint) to authenticated;
grant execute on function es_mi_solicitud(bigint) to service_role;
revoke execute on function marcar_publicacion(uuid,text,jsonb) from public, anon, authenticated;
grant execute on function marcar_publicacion(uuid,text,jsonb) to service_role;
revoke execute on function notificar_evento_push() from public, anon, authenticated;
grant execute on function notificar_evento_push() to service_role;
revoke execute on function novedades_a_mandar(text,integer) from public, anon, authenticated;
grant execute on function novedades_a_mandar(text,integer) to service_role;
revoke execute on function proteger_mensajes() from public, anon, authenticated;
grant execute on function proteger_mensajes() to service_role;
revoke execute on function proteger_perfil_proveedor() from public, anon, authenticated;
grant execute on function proteger_perfil_proveedor() to service_role;
revoke execute on function proveedor_visible(bigint) from public, anon, authenticated;
grant execute on function proveedor_visible(bigint) to public;
grant execute on function proveedor_visible(bigint) to anon;
grant execute on function proveedor_visible(bigint) to authenticated;
grant execute on function proveedor_visible(bigint) to service_role;
revoke execute on function registrar_push_subscripcion(text,text,text,text) from public, anon, authenticated;
grant execute on function registrar_push_subscripcion(text,text,text,text) to authenticated;
grant execute on function registrar_push_subscripcion(text,text,text,text) to service_role;
revoke execute on function solicitud_visible(bigint) from public, anon, authenticated;
grant execute on function solicitud_visible(bigint) to public;
grant execute on function solicitud_visible(bigint) to anon;
grant execute on function solicitud_visible(bigint) to authenticated;
grant execute on function solicitud_visible(bigint) to service_role;
revoke execute on function soy_parte_del_match(bigint) from public, anon, authenticated;
grant execute on function soy_parte_del_match(bigint) to public;
grant execute on function soy_parte_del_match(bigint) to anon;
grant execute on function soy_parte_del_match(bigint) to authenticated;
grant execute on function soy_parte_del_match(bigint) to service_role;
revoke execute on function sumar_trabajo() from public, anon, authenticated;
grant execute on function sumar_trabajo() to service_role;
revoke execute on function video_jobs_tocar_actualizado_en() from public, anon, authenticated;
grant execute on function video_jobs_tocar_actualizado_en() to public;
grant execute on function video_jobs_tocar_actualizado_en() to anon;
grant execute on function video_jobs_tocar_actualizado_en() to authenticated;
grant execute on function video_jobs_tocar_actualizado_en() to service_role;

-- ===== Storage =====
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('publicaciones', 'publicaciones', true, 5242880, '{image/jpeg,image/png,image/webp}') on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('videos-generados', 'videos-generados', true, null, NULL) on conflict (id) do nothing;

-- ===== Configuración de roles =====
alter role anon set statement_timeout = '3s';
alter role authenticated set statement_timeout = '8s';
